return {
    {
        Name = "Bombardini Gusini",
        Image = "rbxassetid://12984122453",
        Sound = "rbxassetid://1234567890",
        Id = 1,
    },

    {
        Name = "Ballerina Cappuccina",
        Image = "rbxassetid://95646003987759",
        Sound = "rbxassetid://1234567890",
        Id = 1,
    },

    {
        Name = "Bombardino Crocodillo",
        Image = "rbxassetid://94587388166653",
        Sound = "rbxassetid://1234567890",
        Id = 1,
    },

    {
        Name = "Skibidi Toilet",
        Image = "rbxassetid://17050154857",
        Sound = "rbxassetid://1234567890",
        Id = 1,
    },
}