return {
    {
        Name = "Bombombini Gusini",
        Image = "rbxassetid://125022796624253",
        Sound = "rbxassetid://103310523064931",
    },

    {
        Name = "Ballerina Cappuccina",
        Image = "rbxassetid://100036505253840",
        Sound = "rbxassetid://133880812583229",
    },
    --[[
    {
        Name = "Lirili Larila",
        Image = "rbxassetid://109301263161580",
        Sound = "rbxassetid://80305239882676",
    },

    {
        Name = "Brr Brr Patapim",
        Image = "rbxassetid://105047276561943",
        Sound = "rbxassetid://133196985206410",
    },
    ]]
    {
        Name = "Tripi Tropi Tropa Tripa",
        Image = "rbxassetid://140198497640204",
        Sound = "rbxassetid://120748803792278",
    },
    --[[
    {
        Name = "Tung Tung Tung Sahoor",
        Image = "rbxassetid://100339141852074",
        Sound = "rbxassetid://102900141625068",
    },
    ]]
    {
        Name = "Cappuccino Assassino",
        Image = "rbxassetid://130301562111098",
        Sound = "rbxassetid://76889141547641",
    },

    {
        Name = "Bananita Dolphinita",
        Image = "rbxassetid://114870540361466",
        Sound = "rbxassetid://77422343422197",
    },
}